language: python
python:
  - '3.5'
  - '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

cache:
  - pip

install:
  - python setup.py install
  - pip install coveralls
  - pip install pytest-cov

before_script:
  - cd test

script:
  - pytest --cov=pyggi

after_success:
  - coveralls

notifications:
  email: false
  slack:
    rooms:
      - coinse:4Uc1Pz7fxX8mxIOcwRAA9iPw
    on_success: change
    on_failure: always
